### ISSUE TITLE
Add lint check to pipeline on push / merge

### ISSUE THREAD

**Issue by ais-one** [es-labs/vue-antd-template#6]

**Comment by ais-one** [comment]
@tiago154 I have accepted and merged and added the `hactocberfest-accepted` label. Please let me know if there is anything else I need to do.

this is my first time doing this and I hope not to miss any steps for contributors

**Comment by tiago154** [comment]
> @tiago154 I have accepted and merged and added the `hactocberfest-accepted` label. Please let me know if there is anything else I need to do.
> 
> this is my first time doing this and I hope not to miss any steps for contributors

Everything ok @ais-one , thank you very much
